services:
  gateway-service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - jpeg

networks:
  jpeg:
    external: true