apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gateway-hc-config
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz 
    port: 8000          
    checkIntervalSec: 15  
    timeoutSec: 5    
    healthyThreshold: 2  
    unhealthyThreshold: 3 